language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add polaris ./
  - asdf list-all polaris
  - asdf plugin-test polaris ./ --asdf-plugin-gitref $TRAVIS_COMMIT 'polaris version --client=true'
os:
  - linux
  - osx
arch:
  - amd64
  - arm64
  - ppc64le
